spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/safe
    username: root
    password: boot
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddlAuto: create-drop
    showSql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect